# Generated by Django 6.0.3 on 2026-03-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('forecast_days', models.IntegerField(default=30)),
                ('model_used', models.CharField(max_length=100)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(default='Unknown', max_length=50)),
                ('total_records', models.IntegerField(default=0)),
                ('forecast_start', models.CharField(blank=True, max_length=50)),
                ('forecast_end', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
